### PR TITLE
Youtube Shorts Blocker #15

### PR DESCRIPTION
**Pull request by shivang21007**
feature - #15 

# Shorts Blocker

This extension removes Youtube Shorts from everywhere; the home page, subscriptions page and even the search results and allows you to be extra Productive.

## How It Works

It simply injects this [short CSS script](./css/blocker.css) when you browse Youtube.

## Requirements

* Chrome 105 and above (due to the [`:has` selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:has))

@nik132-eng Please review it :)

### CODE REVIEW

**Comment by nik132-eng** [comment]
please provide a short video and comment down here

**Comment by shivang21007** [comment]
@nik132-eng  I have uploaded the video, please review it.

https://github.com/nik132-eng/chrome-extensions/assets/98748694/433de92b-57dc-4f35-ba71-dea7dc399f43

**Comment by nik132-eng** [comment]
> @nik132-eng I have uploaded the video, please review it.
> 
>  Youtube.Shorts.Blocker.15.by.shivang21007.Pull.Request.31.nik132-eng_chrome-extensions.-.Brave.2023-12-23.18-54-06.mp4

Thank you for the video submission but I want to add your extension after clicking the extension it should remove the shorts. Not adding the script in the console

**Review by nik132-eng — DISMISSED** [review]

**Comment by shivang21007** [comment]
> > @nik132-eng I have uploaded the video, please review it.
> > Youtube.Shorts.Blocker.15.by.shivang21007.Pull.Request.31.nik132-eng_chrome-extensions.-.Brave.2023-12-23.18-54-06.mp4
> 
> Thank you for the video submission but I want to add your extension after clicking the extension it should remove the shorts. Not adding the script in the console

i just showed you how my script work, not the actual workflow. once you add it in chrome , it will do it this way and your short willdisapear, you just have to enable it like a actual chrome extension.

**Comment by nik132-eng** [comment]
> > > @nik132-eng I have uploaded the video, please review it.
> > > Youtube.Shorts.Blocker.15.by.shivang21007.Pull.Request.31.nik132-eng_chrome-extensions.-.Brave.2023-12-23.18-54-06.mp4
> > 
> > 
> > Thank you for the video submission but I want to add your extension after clicking the extension it should remove the shorts. Not adding the script in the console
> 
> @nik132-eng i just showed you how my script work, not the actual workflow. once you add it in chrome , it will do it this way and your short will disapear, you just have to enable it like a actual chrome extension.

yes I know but add the video which I mentioned before, add your extension in the developer mode, and show It

**Comment by shivang21007** [comment]
> > > > @nik132-eng I have uploaded the video, please review it.
> > > > Youtube.Shorts.Blocker.15.by.shivang21007.Pull.Request.31.nik132-eng_chrome-extensions.-.Brave.2023-12-23.18-54-06.mp4
> > > 
> > > 
> > > Thank you for the video submission but I want to add your extension after clicking the extension it should remove the shorts. Not adding the script in the console
> > 
> > 
> > @nik132-eng i just showed you how my script work, not the actual workflow. once you add it in chrome , it will do it this way and your short will disapear, you just have to enable it like a actual chrome extension.
> 
> yes I know but add the video which I mentioned before, add your extension in the developer mode, and show It

okay :)

**Comment by shivang21007** [comment]
@nik132-eng Here you go ....


https://github.com/nik132-eng/chrome-extensions/assets/98748694/88ae1ca2-482a-4f7e-9200-91b00ac400fe

**Review by nik132-eng — APPROVED** [review]

**Comment by shivang21007** [comment]
@nik132-eng Also please label this PR and issue under Kwoc23

**Pull request merged**
